vim9script
# Title: Vim Init File
# Author: Mike Grammes
#
# Set defaults
source $VIMRUNTIME/defaults.vim

# Turn on line numbers and relative line numbers
set number relativenumber
# Set a group for documentation line numbers
augroup vim help
	autocmd!
	autocmd FileType help setlocal number
#	autocmd FileType help setlocal relativenumber
augroup END

# Disable compatibility with vi which can cause unexpected issues
set nocompatible

# Enable type file detection. Vim will be able to try to detect file type
filetype on

# Enable plugins and load plugin for the detected file type.
filetype plugin on

# Load an indent file for the detected file type.
filetype indent on

# Turn syntax highlighting on.
syntax on

# While searching through a file incrementally highlight matches
set incsearch

# Ignore capital letters during search.
set ignorecase

# Overide the ignorecase option if searching for capital letters.
# This will allow you to search specifically for capital letters.
set smartcase

# Hilight all matches in a search.
set hlsearch

# Show partial command you type in the last line of the screen.
set showcmd

# Show the mode you are in on the last line.
set showmode

# Set new popup menu
set wildoptions=pum

# Set colorscheme
set background=dark
colorscheme torte
# Set tabs to spaces
set expandtab
# Set tab size to 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

# Make :grep run ripgrep to search files
set grepprg=rg\ --vimgrep\ --smart-case\ --follow

# Settings for Calendar.Vim

# Google Calendar Integration
g:calendar_google_calendar = 1

# Google Tast Integration
g:calendar_google_task = 1

# Get Credentials from .cach/calendar.vim/credentials.vim
source ~/.cache/calendar.vim/credentials.vim

# Wiki.vim Settings

# Set root directory for wiki
g:wiki_root = '~/wiki'

